---
- import_tasks: docker.yml
  tags: [docker]

- import_tasks: directories.yml
  tags: [directories]

- import_tasks: boot_files.yml
  tags: [boot_files]

- import_tasks: configs.yml
  tags: [configs]

- import_tasks: compose.yml
  tags: [compose]
